#!/bin/bash

taskset -c 16-23 $JAVA_HOME/bin/java -jar nb5.jar vector-search.yaml default.main \
 errors=counter \
 driverconfig=driver-config.json \
 dimensions=384 \
 main-cycles=10M keyspace=wikipedia \
 -v --show-stacktraces
